### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by kbudkiewicz** [standardebooks/bertrand-russell_roads-to-freedom#1]
While reading I found a typo in the book. It probably comes from PG, which has the same error. I've checked both IA sources ([here](https://archive.org/details/proposedroadstof00russuoft/page/170/mode/2up) and [here](https://archive.org/details/roadstofreedomso00russuoft/page/174/mode/2up)) and they seem to agree that the following paragraph in `.../chapter-7.xhtml`:
> is to he feared that

should be:
> is to **be** feared that

**Comment by acabal** [comment]
Thanks, this should be fixed now!
